name: Todo Server Deploy
on: 
  push:
    branches:
      feature-v1.0.0
jobs:
  pull_code: 
    name: pull_code
    runs-on: centos8
    steps:
      - name: pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # 服务器ip
          username: ${{ secrets.HOST_USERNAME }} # 服务器登录用户名
          password: ${{ secrets.HOST_PASSWORD }} # 服务器登录密码
          port: ${{ secrets.HOST_PORT }} # 服务器ssh端口
          script:
            cd /root/code/todo
            git pull
  build:
    name: build_server
    needs: pull_code
    runs-on: centos8
    steps:
      - name: deply
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # 服务器ip
          username: ${{ secrets.HOST_USERNAME }} # 服务器登录用户名
          password: ${{ secrets.HOST_PASSWORD }} # 服务器登录密码
          port: ${{ secrets.HOST_PORT }} # 服务器ssh端口
          script:
            docker-compose up -d