name: Todo Server Deploy
on: 
  push:
    branches:
      feature-v1.0.0
jobs:
  pull_code: 
    name: pull_code
    runs-on: ubuntu-latest
    steps:
      - name: pull
        uses: actions/pull@master
        with:
          host: ${{ secrets.HOST }} # 服务器ip
          username: ${{ secrets.HOST_USERNAME }} # 服务器登录用户名
          password: ${{ secrets.HOST_PASSWORD }} # 服务器登录密码
          port: ${{ secrets.HOST_PORT }} # 服务器ssh端口
          script:
            cd /root/code/todo
            git pull
      - name: deploy
        uses: actions/deploy@master
        with:
          host: ${{ secrets.HOST }} # 服务器ip
          username: ${{ secrets.HOST_USERNAME }} # 服务器登录用户名
          password: ${{ secrets.HOST_PASSWORD }} # 服务器登录密码
          port: ${{ secrets.HOST_PORT }} # 服务器ssh端口
          script:
            cd /root/code/todo/server
            docker-compose up -d